### ISSUE TITLE
시계 타이머 만들기

### ISSUE THREAD

**Issue by lee-yun-pyo** [lee-yun-pyo/ExamTimer#3]
## 📌 To-do
- [ ] 시계 타이머 컴포넌트 만들기
- [ ] 초침 움직임 기능 고려
- [ ] 초기화 및 멈춤 기능 구현
