### ISSUE TITLE
홈 화면 기능 개발

### ISSUE THREAD

**Issue by lee-yun-pyo** [lee-yun-pyo/ExamTimer#8]
## 📌 To-do
- [x] 홈 화면 페이지 UI 구성
- [x] 모달 컴포넌트 생성 (Portal 이용)
- [x] 커스텀 설정 기능 구현

## 💡 고려사항
- 커스텀 설정 기능 구현 및 모달 생성 시 prop 전달 고려
